# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
# 1+2+3+4+5+6+7 = 28

# What is the value of the first triangle number to have over five hundred divisors?
import math


def count_divisors(num):

    count = 0
    sqrt_n = int(math.sqrt(num))

    for i in range(1, sqrt_n + 1):
        if num % i == 0:
            count += 2  

    if sqrt_n * sqrt_n == num: # x * x case
        count -= 1  
    return count

n = 1
triangle = 1

while True:
    x = count_divisors(triangle)
    if x > 500:
        break
    n += 1
    triangle += n

print(triangle)
